name: prism
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  csv: ^6.0.0
  drift: ^2.29.0
  file_picker: ^8.0.0
  fl_chart: ^1.1.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  freezed_annotation: ^3.1.0
  go_router: ^17.0.0
  intl: ^0.20.2
  math_expressions: ^2.6.0
  path: ^1.9.1
  path_provider: ^2.1.5
  riverpod_annotation: ^3.0.3
  share_plus: ^10.0.0
  shared_preferences: ^2.5.4
  sqlite3_flutter_libs: ^0.5.40
  uuid: ^4.5.2

dev_dependencies:
  build_runner: ^2.10.4
  drift_dev: ^2.29.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  json_annotation: ^4.9.0
  json_serializable: ^6.11.2
  riverpod_generator: ^3.0.3
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true
